---
title: "Ab titer data comparision"
output: html_notebook
---

```{r echo=FALSE}
library("tidyverse")
library(hrbrthemes)
library(jsonlite)

options(warn=-1)
```



## reading datasets
```{r echo=FALSE}
setwd("/home/pramod/Documents/cmipb_project/ab_plate_normalisation")
data_2021_metadata <- read_tsv("metadata_cmipb_2021.csv")
data_2020_metadata <- read_csv("metadata_cmipb_2020.csv")

#data_2021 <- read_tsv("2021_ab_titer_032422.tsv")  %>%
data_2021 <- read_tsv("2021_ab_titer_032522_one_lod.tsv")  %>%
   rename(specimen_id = Sample_ID) %>%
    mutate(subject_id = substr(specimen_id, 1,4),
           visit = substr(specimen_id, 9,9),
           dpb= case_when(
                visit == 1 ~ 0,
                visit == 2 ~ 1,
                visit == 3 ~ 3,
                visit == 4 ~ 7,
                visit == 5 ~ 14,
                visit == 6 ~ 30,
                visit == 7 ~ 90,
           ),
           isotype_antigen = paste0(isotype,"_",antigen)
  ) 
  
    
json_subject <- fromJSON("subject.json")
json_specimen <- fromJSON("specimen.json")
subject_specimen  <- left_join(json_specimen, json_subject)

data_2020 <- read_csv("2020LD_ab_titer.csv") %>%
  left_join(subject_specimen) %>%
  mutate(
    antigen = replace(antigen, antigen =='1% PFA PT', 'PT'),
    isotype_antigen = paste0(isotype,"_",antigen))
  
data_2020 <- data_2020 %>%
  mutate(
    #lower_limit_of_detection = if_else(isotype_antigen == "IgG_FHA", 4.679535, lower_limit_of_detection), ## Correct LOD for IgG_FHA
    ab_titer = if_else(ab_titer < lower_limit_of_detection, lower_limit_of_detection, ab_titer)
  )

```

###
```{r}

#input_data_1 <- input_data[input_data$isotype_antigen == "IgG3_PT",]
## Setting MFI zero values to lower limit of detection
df_lod_calculated_2020 <- data_2020 %>%
  group_by(isotype_antigen) %>%
  mutate(lod = min(ab_titer[ab_titer>0]),
         MFI_lod = if_else(ab_titer == 0 | is.na(ab_titer) == TRUE, lod, ab_titer)
         ) %>%
  ungroup() 

df_d0_median_2020  <- df_lod_calculated_2020 %>%
  filter(planned_day_relative_to_boost == 0) %>%
  group_by(isotype_antigen) %>%
  summarise(
    overall_median_d0 = median(MFI_lod),
    #overall_iqr_d0 = IQR(MFI_lod)
  ) 


data_2020_new   <-  left_join(df_lod_calculated_2020 , df_d0_median_2020 , by = "isotype_antigen") %>%
  mutate(
    ab_titer_median = MFI_lod / overall_median_d0,
    #ab_titer_iqr = MFI_lod / overall_iqr_d0
  )


#df_d0_median_2020 %>%
  #ggplot(aes(log(overall_median_d0), log(overall_iqr_d0))) + geom_point() + theme_ipsum() + geom_smooth() 
  
medians_d0_2020 <- data_2020_new %>%
  group_by(isotype_antigen) %>%
  filter(planned_day_relative_to_boost == 0) %>%
  summarize(          median_d0 = median(ab_titer_median)
            )

medians_d0_2020
```


```{r echo=FALSE}
common_antigens <- intersect(data_2020_new$antigen, data_2021$antigen)
common_isotypes <- intersect(data_2020_new $isotype, data_2021$isotype)

data_2021_common <- data_2021 %>%
  filter(antigen %in% common_antigens & isotype %in% common_isotypes) %>%
  mutate(dataset = "2021") 

data_2020_common <- data_2020_new %>%
  filter(antigen %in% common_antigens & isotype %in% common_isotypes) %>%
  mutate(dataset = "2020")
  
data_2020_common_control <- data_2020_common %>%
  filter(subject_id %in% c('2', '8'))

data_2021_common_control <- data_2021_common %>%
  filter(subject_id %in% c('1686', '2631'))

#data_2020_2021_common <- rbind(data_2020_common, data_2021_common)
#Our transformation function
scaleFUN <- function(x) sprintf("%.3f", x)
```



```{r}
for(select.isotype in c("IgG"))
{
  
#png(filename=paste0("2020",select.isotype,".png"), width=600, height=700)  
  
#select.isotype_antigen = "IgG1" 
plot1 <- data_2020_common %>%
  filter(isotype == select.isotype, planned_day_relative_to_boost < 50) %>%
  #filter(ab_titer > lower_limit_of_detection)
  filter(antigen %in% unique(data_2021_common[data_2021_common$isotype == select.isotype,]$antigen)) %>%
  ggplot(., aes(y=ab_titer_median, x=planned_day_relative_to_boost)) +
    ggtitle(paste0("2020 Antibody titers (" , select.isotype, ")")) +
    geom_point() + 
    geom_line(aes(group=subject_id),linetype = "dotted")+
    labs(x = "Day post boost", y = "Ab titer") + 
    geom_smooth() +
    theme_bw() +
    facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
    theme(strip.background = element_blank(), strip.placement = "outside") +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)


plot(plot1)
#dev.off()
#png(filename=paste0("2021",select.isotype,".png"), width=600, height=700)  
plot2 <- data_2021_common %>%
  filter(isotype == select.isotype, dpb < 50) %>%
  #filter(ab_titer_median < 1)  %>%
  filter(antigen %in% unique(data_2020_common[data_2020_common$isotype == select.isotype,]$antigen)) %>%
  #ggplot(., aes(y=log2(ab_titer_median), x=dpb)) +
  ggplot(., aes(y=ab_titer_median, x=dpb)) +
    ggtitle(paste0("2021 Antibody titers (" , select.isotype, ")")) +
    geom_point() + 
    geom_line(aes(group=subject_id),linetype = "dotted")+
    labs(x = "Day post boost", y = "Ab titer") + 
    geom_smooth() +
    theme_bw() +
    facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
    theme(strip.background = element_blank(), strip.placement = "outside") +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)


plot(plot2)
#dev.off()
}
```


## Ploting in log scale
```{r}
for(select.isotype in c("IgG1", "IgG2", "IgG3", "IgG4"))
{
  
#png(filename=paste0("2020",select.isotype,".png"), width=600, height=700)  
  
#select.isotype_antigen = "IgG1" 
plot1 <- data_2020_common %>%
  filter(isotype == select.isotype, planned_day_relative_to_boost < 50) %>%
  filter(antigen %in% c("DT", "FHA", "FIM2/3"))  %>%
  filter(antigen %in% unique(data_2021_common[data_2021_common$isotype == select.isotype,]$antigen)) %>%
  ggplot(., aes(y=(ab_titer_median), x=planned_day_relative_to_boost)) +
    ggtitle(paste0("2020 Antibody titers (" , select.isotype, ")")) +
    geom_point() + 
    geom_line(aes(group=subject_id),linetype = "dotted")+
    labs(x = "Day post boost", y = "Ab titer") + 
    geom_smooth() +
    theme_bw() +
    facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
    theme(strip.background = element_blank(), strip.placement = "outside") +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)


plot(plot1)
#dev.off()
#png(filename=paste0("2021",select.isotype,".png"), width=600, height=700)  
plot2 <- data_2021_common %>%
  filter(isotype == select.isotype, dpb < 50) %>%
  filter(antigen %in% c("DT", "FHA", "FIM2/3"))  %>%
  filter(antigen %in% unique(data_2020_common[data_2020_common$isotype == select.isotype,]$antigen)) %>%
  #ggplot(., aes(y=log2(ab_titer_median), x=dpb)) +
  ggplot(., aes(y=ab_titer_median, x=dpb)) +
    ggtitle(paste0("2021 Antibody titers (" , select.isotype, ")")) +
    geom_point() + 
    geom_line(aes(group=subject_id),linetype = "dotted")+
    labs(x = "Day post boost", y = "Ab titer") + 
    geom_smooth() +
    theme_bw() +
    facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
    theme(strip.background = element_blank(), strip.placement = "outside") +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)


plot(plot2)
#dev.off()
}




```
## Ploting in log scale
```{r}
for(select.isotype in c("IgG1", "IgG2", "IgG3", "IgG4"))
{
  
#png(filename=paste0("2020",select.isotype,".png"), width=600, height=700)  
  
#select.isotype_antigen = "IgG1" 
plot1 <- data_2020_common %>%
  filter(isotype == select.isotype, planned_day_relative_to_boost < 50) %>%
  filter(antigen %in% c("OVA", "PRN", "PT", "TT"))  %>%
  filter(antigen %in% unique(data_2021_common[data_2021_common$isotype == select.isotype,]$antigen)) %>%
  ggplot(., aes(y=(ab_titer_median), x=planned_day_relative_to_boost)) +
    ggtitle(paste0("2020 Antibody titers (" , select.isotype, ")")) +
    geom_point() + 
    geom_line(aes(group=subject_id),linetype = "dotted")+
    labs(x = "Day post boost", y = "Ab titer") + 
    geom_smooth() +
    theme_bw() +
    facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
    theme(strip.background = element_blank(), strip.placement = "outside") +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)


plot(plot1)
#dev.off()
#png(filename=paste0("2021",select.isotype,".png"), width=600, height=700)  
plot2 <- data_2021_common %>%
  filter(isotype == select.isotype, dpb < 50) %>%
  filter(antigen %in% c("OVA", "PRN", "PT", "TT"))  %>%
  filter(antigen %in% unique(data_2020_common[data_2020_common$isotype == select.isotype,]$antigen)) %>%
  #ggplot(., aes(y=log2(ab_titer_median), x=dpb)) +
  ggplot(., aes(y=ab_titer_median, x=dpb)) +
    ggtitle(paste0("2021 Antibody titers (" , select.isotype, ")")) +
    geom_point() + 
    geom_line(aes(group=subject_id),linetype = "dotted")+
    labs(x = "Day post boost", y = "Ab titer") + 
    geom_smooth() +
    theme_bw() +
    facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
    theme(strip.background = element_blank(), strip.placement = "outside") +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)


plot(plot2)
#dev.off()
}




```
```{r}

data_plot_2021_medians_d0  <- data_2021 %>%
  group_by(isotype_antigen) %>%
  filter(dpb == 0)  %>%
  summarise(median_d0 = median(ab_titer_median))

data_plot_2021_medians_d0
```
## Plot tail distribution

```{r}
for(select.isotype in c("IgG"))
{
  
p1 <- data_2020_common %>%
  #filter(antigen %in% unique(data_2021_common))
  filter(isotype == select.isotype) %>%
  arrange(desc(ab_titer_median)) %>%
  ggplot(aes(y=ab_titer_median)) +  stat_ecdf(geom = "point")+
  labs(y = "Ab titer", x = "Percentile")+ ggtitle(paste0("2020 Antibody titers (" , select.isotype, ")")) + theme_bw() +
  facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)
  
  #ggplot(aes(x=ab_titer_median, y=Sample_ID)) +  geom_point()
plot(p1)


p1 <- data_2021_common %>%
  #filter(antigen %in% unique(data_2020_common)) %>%
  filter(antigen %in% unique(data_2020_common[data_2020_common$isotype == select.isotype,]$antigen)) %>%
  filter(isotype == select.isotype) %>%
  arrange(desc(ab_titer_median)) %>%
  ggplot(aes(y=ab_titer_median)) +  stat_ecdf(geom = "point")+
  labs(y = "Ab titer", x = "Percentile")+ ggtitle(paste0("2021 Antibody titers (" , select.isotype, ")")) + theme_bw() +
  facet_wrap(. ~ antigen, scales = "free", nrow = 1) +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)
  
  #ggplot(aes(x=ab_titer_median, y=Sample_ID)) +  geom_point()
plot(p1)
}


```

```{r}
for(select.isotype in c("IgG1", "IgG2", "IgG3", "IgG4"))
{
  
p1 <- data_2020_common %>%
  #filter(antigen %in% unique(data_2021_common))
  filter(isotype == select.isotype) %>%
  arrange(desc(ab_titer_median)) %>%
  ggplot(aes(y=ab_titer_median)) +  stat_ecdf(geom = "point")+
  labs(y = "Ab titer", x = "Percentile")+ ggtitle(paste0("2020 Antibody titers (" , select.isotype, ")")) + theme_bw() +
  facet_wrap(. ~ antigen, scales = "free", nrow = 2) +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)
  
  #ggplot(aes(x=ab_titer_median, y=Sample_ID)) +  geom_point()
plot(p1)

p2 <- data_2021_common %>%
  #filter(antigen %in% unique(data_2020_common)) %>%
  filter(antigen %in% unique(data_2020_common[data_2020_common$isotype == select.isotype,]$antigen)) %>%
  filter(isotype == select.isotype) %>%
  arrange(desc(ab_titer_median)) %>%
  ggplot(aes(y=ab_titer_median)) +  stat_ecdf(geom = "point")+
  labs(y = "Ab titer", x = "Percentile")+ ggtitle(paste0("2021 Antibody titers (" , select.isotype, ")")) + theme_bw() +
  facet_wrap(. ~ antigen, scales = "free", nrow = 2) +
  scale_y_continuous(trans = 'log2', labels=scaleFUN)
  
  #ggplot(aes(x=ab_titer_median, y=Sample_ID)) +  geom_point()
plot(p2)
}
```


```{r}
data_2020_common %>%
  filter(isotype != "IgE" & planned_day_relative_to_boost==0) %>%
  mutate(titer = if_else(ab_titer <= lower_limit_of_detection, 0, ab_titer),
         titer_lod = if_else(ab_titer <= lower_limit_of_detection, lower_limit_of_detection, ab_titer),
           ) %>%
  group_by(isotype_antigen) %>%
  summarise(median_lod_T= median(titer_lod), median_lod_F= median(titer[titer>0]))
```


```{r}

```

